[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line_length = 120
skip-string-normalization = true

[tool.mypy]
python_version = 3.10
disallow_untyped_defs = true
ignore_missing_imports = true
strict = true
exclude = ["tests"]

[tool.pytest.ini_options]
