"""
Link to Itential Docs: https://docs.itential.com/2020.2/api/adapter-automation_gateway/

Implemented  Doc String  Tests
    [ ]         [ ]       [ ]   addDeviceToDeviceGroup
    [ ]         [ ]       [ ]   applyTerraform
    [ ]         [ ]       [ ]   connectDevice
    [ ]         [ ]       [ ]   createDevice
    [ ]         [ ]       [ ]   createDeviceGroup
    [ ]         [ ]       [ ]   createDeviceRaw
    [ ]         [ ]       [ ]   deleteDevice
    [ ]         [ ]       [ ]   deleteDeviceFromDeviceGroup
    [ ]         [ ]       [ ]   deleteDeviceGroup
    [ ]         [ ]       [ ]   destroyTerraform
    [ ]         [ ]       [ ]   dryRunPlaybook
    [ ]         [ ]       [ ]   getCollectionModule
    [ ]         [ ]       [ ]   getCollectionModules
    [ ]         [ ]       [ ]   getCollectionRole
    [ ]         [ ]       [ ]   getCollectionRoles
    [ ]         [ ]       [ ]   getCollections
    [ ]         [ ]       [ ]   getConfig
    [ ]         [ ]       [ ]   getDevice
    [ ]         [ ]       [ ]   getDeviceDetailsRaw
    [ ]         [ ]       [ ]   getDeviceGroup
    [ ]         [ ]       [ ]   getDeviceGroups
    [ ]         [ ]       [ ]   getDeviceHealth
    [ ]         [ ]       [ ]   getDeviceInfo
    [ ]         [ ]       [ ]   getDevices
    [ ]         [ ]       [ ]   getDevicesDetailsRaw
    [ ]         [ ]       [ ]   getDevicesFiltered
    [ ]         [ ]       [ ]   getModule
    [ ]         [ ]       [ ]   getModules
    [ ]         [ ]       [ ]   getNornirModule
    [ ]         [ ]       [ ]   getNornirModules
    [ ]         [ ]       [ ]   getPlaybook
    [ ]         [ ]       [ ]   getPlaybooks
    [ ]         [ ]       [ ]   getPronghorn
    [ ]         [ ]       [ ]   getRole
    [ ]         [ ]       [ ]   getRoles
    [ ]         [ ]       [ ]   getScript
    [ ]         [ ]       [ ]   getScripts
    [ ]         [ ]       [ ]   getTerraform
    [ ]         [ ]       [ ]   getTerraforms
    [ ]         [ ]       [ ]   initTerraform
    [ ]         [ ]       [ ]   isAlive
    [ ]         [ ]       [ ]   netmikoSendCommand
    [ ]         [ ]       [ ]   netmikoSendConfig
    [ ]         [ ]       [ ]   planTerraform
    [ ]         [ ]       [ ]   refreshCollections
    [ ]         [ ]       [ ]   refreshInventory
    [ ]         [ ]       [ ]   refreshModules
    [ ]         [ ]       [ ]   refreshNornirModules
    [ ]         [ ]       [ ]   refreshPlaybooks
    [ ]         [ ]       [ ]   refreshRoles
    [ ]         [ ]       [ ]   refreshScripts
    [ ]         [ ]       [ ]   restoreConfig
    [ ]         [ ]       [ ]   runCollectionModule
    [ ]         [ ]       [ ]   runCollectionRole
    [ ]         [ ]       [ ]   runCommand
    [ ]         [ ]       [ ]   runModule
    [ ]         [ ]       [ ]   runNornirModule
    [ ]         [ ]       [ ]   runPlaybook
    [ ]         [ ]       [ ]   runRole
    [ ]         [ ]       [ ]   runScript
    [ ]         [ ]       [ ]   runScriptEnv
    [ ]         [ ]       [ ]   setConfig
    [ ]         [ ]       [ ]   updateDevice
    [ ]         [ ]       [ ]   updateDeviceGroup
"""