name: Lint

on:
  pull_request:
    branches:
      - development

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: psf/black@stable
        with:
          options: "--check --verbose --color"
          version: "22.6.0"