name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
      - uses: actions/checkout@v2

      - name: Install dependencies
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          version: "22.6.0"