name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev_requirements.txt

    - name: Lint with Ruff
      run: ruff check

    - name: Format with Black
      run: black . --check

#     Skipping mypy section until we can get to 0 issues.
#    - name: Type check with MyPy
#      run: mypy .

    - name: Test and Coverage
      run: |
        coverage run -m unittest
        coverage html
        coverage report