name: Code Quality Check

on:
  push:
    branches:
      - github-actions-testing

jobs:
  Code-Quality-Check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==22.6.0 mypy isort

      - name: Lint with Black
        run: |
          black --check --color .

#      - name: Run Mypy
#        run: |
#          mypy .

      - name: Run isort
        run: |
          isort --check-only .
