name: Code Quality Check
on: [push]
jobs:
  Code-Quality-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
      - run: pip install black==22.6.0
      - name: Change directory
        run: |
          cd ${{ github.workspace }}
      - name: Check directory
        run: | 
          pwd
      - name: Run Black
        run: |
          black .
